---
title: "SDL_TS"
author: "Delin Sun"
date: "2023-08-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This R Markdown document aims to collect atlas-based time series data from the ENIGMA PGC PTSD project (Duke only)

## Packages
```{r, echo=FALSE}
if (!require("pacman")) {
  install.packages("pacman")
} # make sure that pacman is installed

pacman::p_load(tidyverse    # data management
)

```

## Parameters
```{r,echo=FALSE}
# directory of data sources
fdir_i <-
  file.path('Z:',
            'Data',
            'Lab',
            'new_halfpipe',
            'Outputs',
            'atlas_conn',
            'Duke')
# directory for data targets
fdir_o <-
  file.path('C:',
            'Users',
            'sunde',
            'Documents',
            'Projects',
            'Alex',
            'Data',
            'ts')

# list all files of interest
fins <-
  fdir_i %>% list.files(pattern = 'corrMatrix_atlas-schaefer2011Combined_timeseries.tsv',
                        full.names = TRUE,
                        recursive = TRUE) # file fullname
```


## Run
```{r,echo=FALSE}
for(fin in fins) {
  # segments of the full path of a file
  fseg <- fin %>% strsplit(split = "/") %>% .[[1]]
  len_fseg <- length(fseg) # length of the file segments
  
  fsite <- fseg[[len_fseg - 2]] # site name
  fname <- fseg[[len_fseg]] # file name
  
  fout <-
    file.path(fdir_o, paste0(fsite, '_', fname)) # fullname of target file
  
  # copy & paste
  file.copy(fin, fout, overwrite = T, copy.date = T)
  
  # print info
  print(paste('From:', fin))
  print(paste('To:', fout))
}
print('###############  Completed: Copy & Paste  ##############'
)

```



